### ISSUE TITLE
Add integration/pull request CI testing for Smoke Framework

### ISSUE THREAD

**Issue by tachyonics** [amzn/smoke-framework#10]
## Description

Add integration tests for the framework

## Exit criteria

The integration tests should-
* pull the latest version of the code or the pull request being submitted
* build the code, run tests and SwiftLint
* Build the change into an example application, make sure application compiles and starts up
* Hit an endpoint on the sample application and verify expected result was returned.

**Comment by meguid** [comment]
@tachyonics I'm interested to help in this.

**Comment by tachyonics** [comment]
@meguid Thanks for the help. I'd be interested in any thoughts you have on the best approach. I was thinking of suggesting going with AWS CodeBuild as that is what I know but I'd be happy to look at other options.

**Comment by meguid** [comment]
@tachyonics I'm not familiar with CodeBuild, but I think Travis CI had better support and free for open source projects.

**Comment by tachyonics** [comment]
Sorry for taking so long for getting back on this. Looks like Travis CI is the better option. I have requested that it be installed on our repositories and then we can set it up.

**Comment by tachyonics** [comment]
Thanks. I've added a basic CI integration that compiles and runs the tests and SwiftLint to confirm that it is working. If you'd like to look at what else can be added that would be great!

**Comment by meguid** [comment]
I checked the CITests script and the travis file and I see they're great. 

I think it'd be better if we applied a test coverage minimum percentage on code, and also I think it'd be better if we limited the "disabled_rules" a bit in Swiftlint and installed it in an "install" step in travis not in the "run" script.

**Comment by tachyonics** [comment]
Those sound good ideas. Is there anything you need from me to look further into this?
