### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by rex-remind101** [amzn/smoke-framework#39]
What's the status of this project?

Also, is Amazon officially backing this?

Thanks

**Comment by tachyonics** [comment]
Hi Rex,

We are currently working forwards a 2.0 release for the SmokeFramework which will move the project onto SwiftNIO 2 as well as some other enhancements.

The SmokeFramework was developed within Amazon (PrimeVideo in particular) and we have open-sourced it as an Amazon repository, with support coming from my team. Is that the level of backing you were asking about or something else?

**Comment by rex-remind101** [comment]
That's great. It only seems like you're working on it though which has been a concern, and more recently commits seem more sparse. So it's hard for me to tell if this is a fun side project or actually tested and used in production.

I've been looking forward to using Swift server side for a long time on AWS. The more assurance I have that Amazon is invested in it the more assurance I have of getting support if/when bugs show up in the SDK.

**Comment by tachyonics** [comment]
That's a fair comment. Unfortunately I have struggled to get interest on my team to more actively contribute, at least recently. That said, my team is using these repositories in production in a not insignificant way so we need to support them from that perspective.

From an Amazon/AWS perspective, we are trying to work towards a more active position. The recently open thread on Amazon Linux 2 support for Swift[1] has been the result of some sustained work by people within AWS to push greater support forward.

[1] https://forums.swift.org/t/building-swift-on-amazon-linux-2/34239

**Comment by joaqo** [comment]
Hey, I was just wondering why did you decide to build this framework in Swift? Why not something more established on the server like Python or Go? Is amazon moving towards Swift or something?

Cheers and thanks for the great repo!

**Comment by rex-remind101** [comment]
Is the struggle to gain interest similar to common complaints on the Swift forums about working with Swift on Linux, complaints that many are currently working on fixing/improving, or something else?

**Comment by BastianInuk** [comment]
@joaqo Simon touched a bit on his decision, in [his talk](https://www.serversideswift.info/2019/speakers/simonpilkington) about Smokes at the latest Server Side Swift conf

**Comment by tachyonics** [comment]
Resolving this issue as it hasn't been commented on in over a year. To summarise, we are actively working on the repository and it is being used in production. Feel free to re-open or create a new issue if there are any other questions or concerns.
