### ISSUE TITLE
Tutorial / basic server

### ISSUE THREAD

**Issue by ilyagru** [amzn/smoke-framework#6]
It would be super useful to add a code example or a tutorial for creating and building a basic project. For example, a web server that returns books on a `GET` request and creates a book on a `POST` request. 😄

**Comment by alexliubj** [comment]
HI @ilyagru 
I wrote a simple example please check here: https://github.com/alexliubj/smoke-framework/tree/Example/Example

**Comment by ilyagru** [comment]
@alexliubj cool, thanks!
